# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_tr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(null=True, related_name='Autor', to='eventos_tr.Autor'),
        ),
    ]
